# Generated by Django 4.2.7 on 2023-12-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='desciption',
            new_name='description',
        ),
    ]
